"""savemessage migration

Revision ID: 649e7e4816a5
Revises: a3c3a7cf674a
Create Date: 2023-05-03 18:41:14.460140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649e7e4816a5'
down_revision = 'a3c3a7cf674a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usermessage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermessage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message', sa.VARCHAR(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
