"""messagechange migration

Revision ID: fca7a34ffaec
Revises: 649e7e4816a5
Create Date: 2023-05-04 12:12:31.750608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca7a34ffaec'
down_revision = '649e7e4816a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermessages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermessages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('time')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
